@startuml

title __BOMBERMAN's Class Diagram__\n

  namespace cz.cvut.bomberman.objects {
    class cz.cvut.bomberman.objects.Bomb {
    }
  }
  

  namespace cz.cvut.bomberman.objects {
    class cz.cvut.bomberman.objects.Boost {
    }
  }
  

  namespace cz.cvut.bomberman.objects {
    enum Boosts {
    }
  }
  

  namespace cz.cvut.bomberman.objects {
    class cz.cvut.bomberman.objects.ExplodeHorizontal {
    }
  }
  

  namespace cz.cvut.bomberman.objects {
    class cz.cvut.bomberman.objects.ExplodeObject {
    }
  }
  

  namespace cz.cvut.bomberman.objects {
    class cz.cvut.bomberman.objects.ExplodeVertical {
    }
  }
  

  namespace cz.cvut.bomberman.objects {
    enum KickMove {
    }
  }
  

  namespace cz.cvut.bomberman.objects {
    class cz.cvut.bomberman.objects.MainObject {
    }
  }
  

  namespace cz.cvut.bomberman.objects {
    class cz.cvut.bomberman.objects.Player {
    }
  }
  

  namespace cz.cvut.bomberman.objects {
    class cz.cvut.bomberman.objects.PlayerControls {
    }
  }
  

  namespace cz.cvut.bomberman.objects {
    class cz.cvut.bomberman.objects.StaticObject {
    }
  }
  

  namespace cz.cvut.bomberman.objects {
    class cz.cvut.bomberman.objects.Wall {
    }
  }
  

  cz.cvut.bomberman.objects.Bomb -up-|> cz.cvut.bomberman.objects.StaticObject
  cz.cvut.bomberman.objects.Bomb o-- cz.cvut.bomberman.objects.KickMove : kickMove
  cz.cvut.bomberman.objects.Bomb o-- cz.cvut.bomberman.objects.Player : owner
  cz.cvut.bomberman.objects.Boost -up-|> cz.cvut.bomberman.objects.StaticObject
  cz.cvut.bomberman.objects.Boost o-- cz.cvut.bomberman.objects.Boosts : boostType
  cz.cvut.bomberman.objects.ExplodeHorizontal -up-|> cz.cvut.bomberman.objects.ExplodeObject
  cz.cvut.bomberman.objects.ExplodeObject -up-|> cz.cvut.bomberman.objects.MainObject
  cz.cvut.bomberman.objects.ExplodeVertical -up-|> cz.cvut.bomberman.objects.ExplodeObject
  cz.cvut.bomberman.objects.Player -up-|> cz.cvut.bomberman.objects.PlayerControls
  cz.cvut.bomberman.objects.Player o-- cz.cvut.bomberman.objects.Bomb : bomb
  cz.cvut.bomberman.objects.PlayerControls -up-|> cz.cvut.bomberman.objects.MainObject
  cz.cvut.bomberman.objects.StaticObject -up-|> cz.cvut.bomberman.objects.MainObject
  cz.cvut.bomberman.objects.StaticObject o-- cz.cvut.bomberman.objects.ExplodeObject : explosion
  cz.cvut.bomberman.objects.Wall -up-|> cz.cvut.bomberman.objects.StaticObject


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
