@startuml

title __OBJECTS's Class Diagram__\n

  namespace cz.cvut.bomberman.objects {
    class cz.cvut.bomberman.objects.Bomb {
        - breakItem : boolean
        - explodeTime : float
        - fireLength : int
        - wasKicked : boolean
    }
  }
  

  namespace cz.cvut.bomberman.objects {
    class cz.cvut.bomberman.objects.Boost {
    }
  }
  

  namespace cz.cvut.bomberman.objects {
    enum Boosts {
    }
  }
  

  namespace cz.cvut.bomberman.objects {
    class cz.cvut.bomberman.objects.ExplodeHorizontal {
        - length : int
        - x : float
        - y : float
    }
  }
  

  namespace cz.cvut.bomberman.objects {
    class cz.cvut.bomberman.objects.ExplodeObject {
        ~ ExplodeObject()
    }
  }
  

  namespace cz.cvut.bomberman.objects {
    class cz.cvut.bomberman.objects.ExplodeVertical {
        - length : int
        - x : float
        - y : float
        ~ ExplodeVertical()
    }
  }
  

  namespace cz.cvut.bomberman.objects {
    enum KickMove {
      ToDown
      ToLeft
      ToRight
      ToUp
      speed
      x
      y
    }
  }
  

  namespace cz.cvut.bomberman.objects {
    class cz.cvut.bomberman.objects.MainObject {
        + x : float
        + y : float
        ~ MainObject()
        ~ MainObject()
    }
  }
  

  namespace cz.cvut.bomberman.objects {
    class cz.cvut.bomberman.objects.Player {
        - bombsAvailable : int
        - bombsMaxNum : int
        - bombsPlaced : int
        - fireLength : int
        - headDirection : int
        - isAlive : boolean
        - kick : boolean
        - speed : float
        - spritePath : String
    }
  }
  

  namespace cz.cvut.bomberman.objects {
    class cz.cvut.bomberman.objects.PlayerControls {
        - down : boolean
        - isUser : boolean
        - left : boolean
        - placeBomb : boolean
        - right : boolean
        - up : boolean
        ~ PlayerControls()
    }
  }
  

  namespace cz.cvut.bomberman.objects {
    class cz.cvut.bomberman.objects.StaticObject {
        + isDestroyable : boolean
        ~ StaticObject()
    }
  }
  

  namespace cz.cvut.bomberman.objects {
    class cz.cvut.bomberman.objects.Wall {
        + isDestroyable : boolean
        + spritePath : String
        + Wall()
    }
  }
  

  cz.cvut.bomberman.objects.Bomb -up-|> cz.cvut.bomberman.objects.StaticObject
  cz.cvut.bomberman.objects.Bomb o-- cz.cvut.bomberman.objects.KickMove : kickMove
  cz.cvut.bomberman.objects.Bomb o-- cz.cvut.bomberman.objects.Player : owner
  cz.cvut.bomberman.objects.Boost -up-|> cz.cvut.bomberman.objects.StaticObject
  cz.cvut.bomberman.objects.Boost o-- cz.cvut.bomberman.objects.Boosts : boostType
  cz.cvut.bomberman.objects.ExplodeHorizontal -up-|> cz.cvut.bomberman.objects.ExplodeObject
  cz.cvut.bomberman.objects.ExplodeObject -up-|> cz.cvut.bomberman.objects.MainObject
  cz.cvut.bomberman.objects.ExplodeVertical -up-|> cz.cvut.bomberman.objects.ExplodeObject
  cz.cvut.bomberman.objects.Player -up-|> cz.cvut.bomberman.objects.PlayerControls
  cz.cvut.bomberman.objects.Player o-- cz.cvut.bomberman.objects.Bomb : bomb
  cz.cvut.bomberman.objects.PlayerControls -up-|> cz.cvut.bomberman.objects.MainObject
  cz.cvut.bomberman.objects.StaticObject -up-|> cz.cvut.bomberman.objects.MainObject
  cz.cvut.bomberman.objects.StaticObject o-- cz.cvut.bomberman.objects.ExplodeObject : explosion
  cz.cvut.bomberman.objects.Wall -up-|> cz.cvut.bomberman.objects.StaticObject


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
